@echo off
cd /d "C:\Users\Егор Алексеевич\MusicBingo"
echo Initializing git repository...
"C:\Program Files\Git\bin\git.exe" init
echo Adding files...
"C:\Program Files\Git\bin\git.exe" add .
echo Making commit...
"C:\Program Files\Git\bin\git.exe" commit -m "Initial commit for MusicBingo game"
echo Setting up remote...
"C:\Program Files\Git\bin\git.exe" remote add origin https://github.com/hellkiper/MusicBingo.git
echo Pushing to GitHub...
"C:\Program Files\Git\bin\git.exe" push -u origin main
echo Done!
pause
